{% set name = "assertpy" %}
{% set version = "0.15" %}
{% set sha256 = "04f52dcd9d60d074b3cfd9f16cc7b4dde4cdf654133562b754062947bc357775" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --record record.txt

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - assertpy

about:
  home: https://github.com/ActivisionGameScience/assertpy
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Assertion library for python unit testing with a fluent API'
  dev_url: https://github.com/ActivisionGameScience/assertpy

extra:
  recipe-maintainers:
    - dwyatte
    - saturnboy
